# Generated by Django 3.0.5 on 2020-05-03 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('climbers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='preference',
            name='duration',
            field=models.PositiveIntegerField(default=60),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='preference',
            name='rest_interval',
            field=models.PositiveIntegerField(default=60),
        ),
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='gender'),
        ),
    ]
