# Generated by Django 3.0.5 on 2020-05-01 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('climbers', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Stat',
            new_name='Measurement',
        ),
        migrations.RenameField(
            model_name='preference',
            old_name='measurement',
            new_name='measurement_system',
        ),
    ]
