# Generated by Django 3.0.5 on 2020-05-01 22:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('climbers', '0002_auto_20200501_1811'),
    ]

    operations = [
        migrations.RenameField(
            model_name='height',
            old_name='stat',
            new_name='measurement',
        ),
        migrations.RemoveField(
            model_name='weight',
            name='stat',
        ),
        migrations.AddField(
            model_name='weight',
            name='measurement',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='climbers.Measurement'),
            preserve_default=False,
        ),
    ]
