# Generated by Django 3.0.5 on 2020-05-03 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('climbers', '0002_auto_20200502_2305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preference',
            name='duration',
            field=models.PositiveIntegerField(default=10),
        ),
    ]
