# Generated by Django 3.0.5 on 2020-05-04 01:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('climbers', '0003_auto_20200502_2305'),
    ]

    operations = [
        migrations.RenameField(
            model_name='preference',
            old_name='rest_between',
            new_name='rest_between',
        ),
    ]
