# Generated by Django 3.0.5 on 2020-05-04 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('climbers', '0004_auto_20200503_2123'),
    ]

    operations = [
        migrations.AddField(
            model_name='preference',
            name='rest_after',
            field=models.PositiveIntegerField(default=60),
        ),
        migrations.AlterField(
            model_name='preference',
            name='rest_between',
            field=models.PositiveIntegerField(default=10),
        ),
    ]
