# Generated by Django 3.0.5 on 2020-05-21 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('climbers', '0005_auto_20200503_2127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='climber',
            name='email',
            field=models.EmailField(error_messages={'unique': 'A user with that username already exists.'}, max_length=150, unique=True, verbose_name='email address'),
        ),
    ]
