# Generated by Django 3.0.5 on 2020-04-28 01:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='birth_date',
            field=models.DateField(default=datetime.datetime(1985, 2, 12, 0, 0), verbose_name='brith date'),
        ),
    ]
