# Generated by Django 3.0.5 on 2020-04-28 05:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_account_birth_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='birth_date',
            field=models.DateField(default=datetime.datetime(1986, 2, 12, 0, 0), verbose_name='brith date'),
        ),
    ]
