# Generated by Django 3.0.5 on 2020-05-03 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='templateworkoutset',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='workoutset',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
