# Generated by Django 3.0.5 on 2020-04-28 05:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0003_auto_20200427_2327'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workoutset',
            old_name='fingers',
            new_name='left_fingers',
        ),
        migrations.RemoveField(
            model_name='workoutset',
            name='hold',
        ),
        migrations.AddField(
            model_name='workoutset',
            name='left_hold',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='left_hold', to='main.Hold'),
        ),
        migrations.AddField(
            model_name='workoutset',
            name='right_fingers',
            field=models.IntegerField(default=4),
        ),
        migrations.AddField(
            model_name='workoutset',
            name='right_hold',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='right_hold', to='main.Hold'),
        ),
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, null=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('custom', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('logged', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='workoutset',
            name='workout',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.Workout'),
            preserve_default=False,
        ),
    ]
