# Generated by Django 3.0.5 on 2020-05-03 21:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_workout_hangboard'),
    ]

    operations = [
        migrations.AddField(
            model_name='templateworkoutset',
            name='next_set',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='template_workout_set_next_set', to='main.TemplateWorkoutSet'),
        ),
        migrations.AddField(
            model_name='templateworkoutset',
            name='previous_set',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='template_workout_set_previous_set', to='main.TemplateWorkoutSet'),
        ),
        migrations.AddField(
            model_name='workoutset',
            name='next_set',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workout_set_next_set', to='main.WorkoutSet'),
        ),
        migrations.AddField(
            model_name='workoutset',
            name='previous_set',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workout_set_previous_set', to='main.WorkoutSet'),
        ),
        migrations.AlterField(
            model_name='templateworkoutset',
            name='left_hold',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='template_workout_set_left_hold', to='main.Hold'),
        ),
        migrations.AlterField(
            model_name='templateworkoutset',
            name='right_hold',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='template_workout_set_right_hold', to='main.Hold'),
        ),
        migrations.AlterField(
            model_name='workoutset',
            name='left_hold',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workout_set_left_hold', to='main.Hold'),
        ),
        migrations.AlterField(
            model_name='workoutset',
            name='right_hold',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workout_set_right_hold', to='main.Hold'),
        ),
    ]
