# Generated by Django 3.0.5 on 2020-05-03 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20200503_1701'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='templateworkoutset',
            name='next_set',
        ),
        migrations.RemoveField(
            model_name='templateworkoutset',
            name='previous_set',
        ),
        migrations.RemoveField(
            model_name='workoutset',
            name='next_set',
        ),
        migrations.RemoveField(
            model_name='workoutset',
            name='previous_set',
        ),
        migrations.AddField(
            model_name='templateworkoutset',
            name='position',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='workoutset',
            name='position',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
