# Generated by Django 3.0.5 on 2020-04-28 05:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20200428_0111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hold',
            name='size',
            field=models.PositiveIntegerField(blank=True, default=20, null=True),
        ),
        migrations.AlterField(
            model_name='workoutset',
            name='left_fingers',
            field=models.PositiveIntegerField(default=4, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='workoutset',
            name='reps',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='workoutset',
            name='rest_interval',
            field=models.PositiveIntegerField(default=60),
        ),
        migrations.AlterField(
            model_name='workoutset',
            name='right_fingers',
            field=models.PositiveIntegerField(default=4, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
