# Generated by Django 3.0.5 on 2020-04-28 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20200428_0134'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutset',
            name='duration',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
