# Generated by Django 3.0.5 on 2020-05-04 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20200503_1740'),
    ]

    operations = [
        migrations.AddField(
            model_name='templateworkoutset',
            name='rest_after',
            field=models.PositiveIntegerField(default=60),
        ),
        migrations.AddField(
            model_name='workoutset',
            name='rest_after',
            field=models.PositiveIntegerField(default=60),
        ),
    ]
