# Generated by Django 3.0.5 on 2020-05-04 01:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20200503_2123'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='templateworkoutset',
            options={'get_latest_by': ('position',)},
        ),
        migrations.AlterModelOptions(
            name='workoutset',
            options={'get_latest_by': ('position',)},
        ),
    ]
