# Generated by Django 3.0.5 on 2020-04-30 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20200429_2232'),
    ]

    operations = [
        migrations.AddField(
            model_name='templateworkout',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='workout',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
