# Generated by Django 3.0.5 on 2020-05-05 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20200503_2137'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='templateworkoutset',
            name='description',
        ),
        migrations.RemoveField(
            model_name='templateworkoutset',
            name='name',
        ),
        migrations.RemoveField(
            model_name='templateworkoutset',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='workoutset',
            name='description',
        ),
        migrations.RemoveField(
            model_name='workoutset',
            name='name',
        ),
        migrations.RemoveField(
            model_name='workoutset',
            name='slug',
        ),
    ]
