# Generated by Django 3.0.5 on 2020-05-05 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20200504_2336'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hold',
            old_name='default_fingers',
            new_name='max_fingers',
        ),
    ]
