# Generated by Django 3.0.5 on 2020-05-05 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20200504_2356'),
    ]

    operations = [
        migrations.AddField(
            model_name='hold',
            name='angle',
            field=models.IntegerField(default=90),
        ),
    ]
