# Generated by Django 3.0.5 on 2020-05-05 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_hold_angle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hold',
            name='angle',
            field=models.IntegerField(default=0),
        ),
    ]
