# Generated by Django 3.0.5 on 2020-05-05 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20200505_0008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hold',
            name='angle',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
