# Generated by Django 3.0.5 on 2020-05-06 06:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0013_auto_20200505_0009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='templateworkoutset',
            name='climber',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='templateworkoutset',
            name='left_hold',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='template_workout_set_left_hold', to='main.Hold'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='templateworkoutset',
            name='right_hold',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='template_workout_set_right_hold', to='main.Hold'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='workoutset',
            name='climber',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='workoutset',
            name='left_hold',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='workout_set_left_hold', to='main.Hold'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='workoutset',
            name='right_hold',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='workout_set_right_hold', to='main.Hold'),
            preserve_default=False,
        ),
    ]
