# Generated by Django 3.0.5 on 2020-05-07 05:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20200506_0206'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workout',
            old_name='scheduled',
            new_name='logged',
        ),
        migrations.AddField(
            model_name='templateworkoutset',
            name='logged',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='workoutset',
            name='logged',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
