# Generated by Django 3.0.5 on 2020-05-07 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20200507_0116'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='hold',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='templateworkoutset',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='workoutset',
            unique_together=set(),
        ),
    ]
