# Generated by Django 3.0.5 on 2020-05-07 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_auto_20200507_1302'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hold',
            old_name='position',
            new_name='position_id',
        ),
    ]
