# Generated by Django 3.0.5 on 2020-05-07 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_auto_20200507_1309'),
    ]

    operations = [
        migrations.AddField(
            model_name='hold',
            name='position',
            field=models.CharField(choices=[('L', 'left'), ('M', 'middle'), ('R', 'right')], default='M', max_length=32),
        ),
    ]
