# Generated by Django 3.0.5 on 2020-05-07 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_hold_position'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='hold',
            unique_together={('position_id', 'hangboard')},
        ),
    ]
