# Generated by Django 3.0.5 on 2020-05-07 23:42

from django.db import migrations
import main.managers


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_auto_20200507_1316'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='exercise',
            managers=[
                ('objects', main.managers.SimpleModelManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='hangboard',
            managers=[
                ('objects', main.managers.SimpleModelManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='hold',
            managers=[
                ('objects', main.managers.SimpleModelManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='holdtype',
            managers=[
                ('objects', main.managers.SimpleModelManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='material',
            managers=[
                ('objects', main.managers.SimpleModelManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='templateworkout',
            managers=[
                ('objects', main.managers.SimpleModelManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='workout',
            managers=[
                ('objects', main.managers.SimpleModelManager()),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='templateworkoutset',
            unique_together={('position', 'workout')},
        ),
        migrations.AlterUniqueTogether(
            name='workoutset',
            unique_together={('position', 'workout')},
        ),
    ]
