# Generated by Django 3.0.5 on 2020-05-09 01:31

from django.db import migrations, models
import main.managers


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_auto_20200508_1735'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='templateworkout',
            managers=[
                ('objects', main.managers.SimpleModelManager()),
            ],
        ),
        migrations.AlterField(
            model_name='templateworkoutset',
            name='logged',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='templateworkoutset',
            name='position',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='workoutset',
            name='logged',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='workoutset',
            name='position',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
