# Generated by Django 3.0.5 on 2020-05-09 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_auto_20200508_2131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='logged',
            field=models.DateTimeField(),
        ),
    ]
