# Generated by Django 3.0.5 on 2020-05-11 20:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_auto_20200508_2133'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='templateworkoutset',
            options={'get_latest_by': ('previous',)},
        ),
        migrations.AlterModelOptions(
            name='workoutset',
            options={'get_latest_by': ('previous',)},
        ),
        migrations.AddField(
            model_name='templateworkoutset',
            name='previous',
            field=models.ForeignKey(blank=True, default=-1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='previous_workoutset', to='main.TemplateWorkoutSet'),
        ),
        migrations.AddField(
            model_name='workoutset',
            name='previous',
            field=models.ForeignKey(blank=True, default=-1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='previous_workoutset', to='main.WorkoutSet'),
        ),
        migrations.AlterUniqueTogether(
            name='templateworkoutset',
            unique_together={('previous', 'workout')},
        ),
        migrations.AlterUniqueTogether(
            name='workoutset',
            unique_together={('previous', 'workout')},
        ),
    ]
