# Generated by Django 3.0.5 on 2020-05-11 22:01

from django.db import migrations
import main.managers


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_auto_20200511_1707'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='templateworkoutset',
            managers=[
                ('objects', main.managers.WorkoutSetManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='workoutset',
            managers=[
                ('objects', main.managers.WorkoutSetManager()),
            ],
        ),
    ]
