# Generated by Django 3.0.5 on 2020-05-11 22:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_auto_20200511_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='templateworkoutset',
            name='left_hold',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='template_workout_set_left_hold', to='main.Hold'),
        ),
        migrations.AlterField(
            model_name='templateworkoutset',
            name='right_hold',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='template_workout_set_right_hold', to='main.Hold'),
        ),
        migrations.AlterField(
            model_name='workoutset',
            name='left_hold',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workout_set_left_hold', to='main.Hold'),
        ),
        migrations.AlterField(
            model_name='workoutset',
            name='right_hold',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workout_set_right_hold', to='main.Hold'),
        ),
    ]
