# Generated by Django 3.0.5 on 2020-05-12 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_auto_20200511_2017'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='templateworkoutset',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='workoutset',
            unique_together=set(),
        ),
    ]
