# Generated by Django 3.0.5 on 2020-05-22 22:37

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import workouts.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, null=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('custom', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('climber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('objects', workouts.managers.SimpleModelManager()),
            ],
        ),
        migrations.CreateModel(
            name='Hangboard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, null=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('custom', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('climber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('objects', workouts.managers.SimpleModelManager()),
            ],
        ),
        migrations.CreateModel(
            name='Hold',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, null=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('custom', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('size', models.PositiveIntegerField(blank=True, default=20, null=True)),
                ('angle', models.IntegerField(blank=True, null=True)),
                ('max_fingers', models.IntegerField(default=4)),
                ('position_id', models.PositiveIntegerField(default=1)),
                ('position', models.CharField(choices=[('L', 'left'), ('M', 'middle'), ('R', 'right')], default='M', max_length=32)),
                ('climber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('hangboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workouts.Hangboard')),
            ],
            managers=[
                ('objects', workouts.managers.SimpleModelManager()),
            ],
        ),
        migrations.CreateModel(
            name='TemplateWorkout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('custom', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(unique=True)),
                ('note', models.TextField(blank=True, default='', null=True)),
                ('completed', models.BooleanField(default=False)),
                ('climber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('objects', workouts.managers.SimpleModelManager()),
            ],
        ),
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('custom', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(unique=True)),
                ('note', models.TextField(blank=True, default='', null=True)),
                ('completed', models.BooleanField(default=False)),
                ('logged', models.DateTimeField()),
                ('difficulty', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('climber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('hangboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workouts.Hangboard')),
            ],
            options={
                'get_latest_by': ('updated',),
            },
            managers=[
                ('objects', workouts.managers.WorkoutManager()),
            ],
        ),
        migrations.CreateModel(
            name='WorkoutSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('left_fingers', models.PositiveIntegerField(default=4, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('right_fingers', models.PositiveIntegerField(default=4, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('rest_between', models.PositiveIntegerField(default=60)),
                ('rest_after', models.PositiveIntegerField(default=60)),
                ('duration', models.PositiveIntegerField(default=0)),
                ('weight', models.IntegerField(default=0)),
                ('reps', models.PositiveIntegerField(default=1)),
                ('completed', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('logged', models.DateTimeField()),
                ('climber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workouts.Exercise')),
                ('left_hold', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workout_set_left_hold', to='workouts.Hold')),
                ('previous', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='previous_workoutset', to='workouts.WorkoutSet')),
                ('right_hold', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workout_set_right_hold', to='workouts.Hold')),
                ('workout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workouts.Workout')),
            ],
            options={
                'get_latest_by': ('previous',),
                'abstract': False,
            },
            managers=[
                ('objects', workouts.managers.WorkoutSetManager()),
            ],
        ),
        migrations.CreateModel(
            name='TemplateWorkoutSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('left_fingers', models.PositiveIntegerField(default=4, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('right_fingers', models.PositiveIntegerField(default=4, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('rest_between', models.PositiveIntegerField(default=60)),
                ('rest_after', models.PositiveIntegerField(default=60)),
                ('duration', models.PositiveIntegerField(default=0)),
                ('weight', models.IntegerField(default=0)),
                ('reps', models.PositiveIntegerField(default=1)),
                ('completed', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('logged', models.DateTimeField()),
                ('climber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workouts.Exercise')),
                ('left_hold', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='template_workout_set_left_hold', to='workouts.Hold')),
                ('previous', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='previous_workoutset', to='workouts.TemplateWorkoutSet')),
                ('right_hold', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='template_workout_set_right_hold', to='workouts.Hold')),
                ('workout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workouts.TemplateWorkout')),
            ],
            options={
                'get_latest_by': ('previous',),
                'abstract': False,
            },
            managers=[
                ('objects', workouts.managers.WorkoutSetManager()),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, null=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('custom', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('climber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('objects', workouts.managers.SimpleModelManager()),
            ],
        ),
        migrations.CreateModel(
            name='HoldType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, null=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('custom', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('climber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('objects', workouts.managers.SimpleModelManager()),
            ],
        ),
        migrations.AddField(
            model_name='hold',
            name='hold_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workouts.HoldType'),
        ),
        migrations.AddField(
            model_name='hangboard',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workouts.Material'),
        ),
        migrations.AlterUniqueTogether(
            name='hold',
            unique_together={('position_id', 'hangboard')},
        ),
    ]
